version: "3.6"

services:
  wintergatan-data-analysis:
    build: .
    image: yanfett/wintergatan-data-analysis:latest
    network_mode: host
    environment:
      - DEBUG_MODE=False
    ports:
      - 5000
